# Generated by Django 4.1.5 on 2023-08-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_outfit',
            field=models.BooleanField(default=False),
        ),
    ]
