# Generated by Django 4.1.5 on 2023-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_id',
            field=models.CharField(blank=True, choices=[('NMA1/0001', 'NMA1/0001'), ('NMA2/0001', 'NMA2/0001'), ('NMA3/0001', 'NMA3/0001'), ('NMA4/0001', 'NMA4/0001'), ('QQN/0001', 'QQN/0001'), ('MRN/0001', 'MRN/0001'), ('AZN/0001', 'AZN/0001'), ('TAS/0001', 'TAS/0001'), ('SKD/0001', 'SKD/0001')], max_length=255, null=True),
        ),
    ]
