# Generated by Django 4.1.5 on 2023-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accountant',
            field=models.BooleanField(default=False),
        ),
    ]
