# Generated by Django 4.1.5 on 2023-12-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_accountant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_accountant',
        ),
    ]
