# Generated by Django 4.1.5 on 2023-12-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_percent_agentcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_of_client',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
