# Generated by Django 4.1.5 on 2023-12-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_num_of_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='num_of_client',
        ),
    ]
