# Generated by Django 4.1.5 on 2023-08-18 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'FastContact',
                'verbose_name_plural': 'FastContact',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Outfit',
                'verbose_name_plural': 'Outfits',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OutfitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('outfit_company', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(choices=[('Jerkin', 'Jerkin'), ('Badge', 'Badge'), ('Bag', 'Bag')], max_length=100)),
                ('number_of_outfit', models.PositiveIntegerField(default=0)),
                ('price_for_one', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'OutfitType',
                'verbose_name_plural': 'OutfitTypes',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OutfitCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('number_of_items', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remained_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit')),
            ],
            options={
                'verbose_name': 'OutfitCalculation',
                'verbose_name_plural': 'OutfitCalculations',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='outfit',
            name='outfit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outfit.outfittype'),
        ),
    ]
