# Generated by Django 4.1.5 on 2023-08-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='outfit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='outfit.outfittype'),
        ),
    ]
