# Generated by Django 4.1.5 on 2023-08-18 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_viewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'FastContact',
                'verbose_name_plural': 'FastContact',
                'ordering': ('-id',),
            },
        ),
    ]
