# Generated by Django 4.1.5 on 2023-07-11 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfitcalculation',
            old_name='quantity_by_room_type',
            new_name='number_of_items',
        ),
    ]
