# Generated by Django 4.1.5 on 2023-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0002_rename_quantity_by_room_type_outfitcalculation_number_of_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
