#!/bin/sh
# entrypoint.sh: runs as the main container process
# Gets passed the container's command as arguments

# Run database migrations.  (Should be safe, if inefficient, to run
# multiple times concurrently.)

python manage.py migrate

# Run whatever command we got passed.
exec "$@"