# Generated by Django 4.1.5 on 2023-07-11 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('aviacompany_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_arrival', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('landing_date', models.DateField(blank=True, null=True)),
                ('landing_time', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_departure', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flighttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepartFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('aviacompany_name', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_arrival', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('landing_date', models.DateField(blank=True, null=True)),
                ('landing_time', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_departure', models.CharField(blank=True, max_length=100, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flighttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
