# Generated by Django 4.1.5 on 2023-07-11 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_returnflight_departflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='AviaCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Avia Company',
                'verbose_name_plural': 'Avia Company',
                'ordering': ('-id',),
            },
        ),
        migrations.RemoveField(
            model_name='departflight',
            name='aviacompany_name',
        ),
        migrations.RemoveField(
            model_name='returnflight',
            name='aviacompany_name',
        ),
        migrations.AddField(
            model_name='departflight',
            name='aviacompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.aviacompany'),
        ),
        migrations.AddField(
            model_name='returnflight',
            name='aviacompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.aviacompany'),
        ),
    ]
