# Generated by Django 4.1.5 on 2023-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0004_flight_price_for_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightcalculation',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
