# Generated by Django 4.1.5 on 2023-07-19 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_remove_departflight_aviacompany_and_more'),
        ('package', '0006_remove_tourpackage_depart_flight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartFlight',
        ),
        migrations.DeleteModel(
            name='ReturnFlight',
        ),
    ]
