# Generated by Django 4.1.5 on 2023-08-15 18:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_delete_departflight_delete_returnflight'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'verbose_name': 'FlightBook',
                'verbose_name_plural': 'FlightBooks',
                'ordering': ('-id',),
            },
        ),
    ]
