# Generated by Django 4.1.5 on 2023-08-18 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('outfit', '0001_initial'),
        ('employee', '0001_initial'),
        ('package', '0001_initial'),
        ('transport', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.guide')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_calculations', to='hotel.hotel')),
                ('outfit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit')),
                ('tourpackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
            ],
            options={
                'verbose_name': 'OtherExpense',
                'verbose_name_plural': 'OtherExpenses',
                'ordering': ('-id',),
            },
        ),
    ]
