# Generated by Django 4.1.5 on 2023-08-10 10:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_delete_departflight_delete_returnflight'),
        ('hotel', '0030_alter_hotel_image'),
        ('employee', '0002_alter_guide_manager'),
        ('outfit', '0003_alter_outfit_full_name'),
        ('package', '0010_remove_tourpackage_guide_tourpackage_guide'),
        ('transport', '0031_alter_transport_image'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.guide')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('outfit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit')),
                ('tourpackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.category'),
        ),
    ]
