# Generated by Django 4.1.5 on 2023-12-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
