# Generated by Django 4.1.5 on 2023-12-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_otherexpense_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherexpense',
            name='office',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
