# Generated by Django 4.1.5 on 2023-08-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_delete_departflight_delete_returnflight'),
        ('employee', '0002_alter_guide_manager'),
        ('package', '0015_contact'),
        ('hotel', '0040_alter_hotel_image'),
        ('transport', '0041_alter_transport_image'),
        ('outfit', '0003_alter_outfit_full_name'),
        ('expense', '0002_category_alter_otherexpense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherexpense',
            name='category',
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.guide'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_calculations', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='outfit.outfit'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='tourpackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='transport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transport.transport'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
