# Generated by Django 4.1.5 on 2023-08-18 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price_for_one', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage')),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VisaCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_day', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remained_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='visa.visa')),
            ],
            options={
                'verbose_name': 'VisaCalculation',
                'verbose_name_plural': 'VisaCalculations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='VisaBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('visa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visa.visa')),
            ],
            options={
                'verbose_name': 'VisaBook',
                'verbose_name_plural': 'VisaBooks',
                'ordering': ('-id',),
            },
        ),
    ]
