# Generated by Django 4.1.5 on 2023-07-03 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('transport_type', models.CharField(choices=[('Bus', 'Bus'), ('Microbus', 'Microbus'), ('Taxi', 'Taxi'), ('Train', 'Train')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='transport_images/.2023-07-03.10-26-59')),
                ('full_name', models.CharField(max_length=100)),
                ('is_acitve', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TransportCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('number_of_days', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remained_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.transport')),
            ],
            options={
                'verbose_name': 'TransportCalculation',
                'verbose_name_plural': 'TransportCalculations',
                'ordering': ('-id',),
            },
        ),
    ]
