# Generated by Django 4.1.5 on 2023-07-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='is_acitve',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='transport',
            name='image',
            field=models.ImageField(null=True, upload_to='transport_images/.2023-07-05.10-19-43'),
        ),
    ]
