# Generated by Django 4.1.5 on 2023-07-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_rename_is_acitve_transport_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='image',
            field=models.ImageField(null=True, upload_to='transport_images/.2023-07-09.08-02-57'),
        ),
    ]
