from django.urls import path
from . import views


urlpatterns = [
    path(
        'tourpackage-landing-search/',
        view=views.tourpackage_landing_search_api_view,
        name='tourpackage_landing_search'
    ),
    path(
        'tourpackage-list/',
        view=views.tourpackage_list_api_view,
        name='tourpackage_list'
    ),
    path(
        'tourpackage-create/',
        view=views.tourpackage_create_api_view,
        name='tourpackage_create'
    ),
    path(
        '<uuid:guid>/tourpackage-detail/',
        view=views.tourpackage_detail_api_view,
        name='tourpackage_detail'
    ),
    path(
        '<uuid:guid>/tourpackage-update/',
        view=views.tourpackage_update_api_view,
        name='tourpackage_update'
    ),
    path(
        '<uuid:guid>/tourpackage-delete/',
        view=views.tourpackage_delete_api_view,
        name='tourpackage_delete'
    ),
    path(
        'tourpackage-analytics/',
        view=views.tourpackage_analytics_api_view,
        name='tourpackage_analytics'
    ),
    path(
        'dashboard/',
        view=views.dashboard_api_view,
        name='dashboard_list'
    ),
    path(
        'report/',
        view=views.report_data_api_view,
        name='report_data'
    ),
    # path(
    #     'export-report/',
    #     view=views.export_report_data_api_view,
    #     name='export_report_data'
    # ),
    path(
        'tourpackagebook-create/',
        view=views.tourpackage_book_create_api_view,
        name='tourpackagebook_create'
    ),
    path(
        'tourpackagebook-list/',
        view=views.tourpackage_book_list_api_view,
        name='tourpackagebook_list'
    ),
    path(
        '<uuid:guid>/tourpackagebook-update/',
        view=views.tourpackage_book_update_api_view,
        name='tourpackagebook_update'
    ),
    path(
        'contact-list/',
        view=views.contact_list_api_view,
        name='contact_list'
    ),
    path(
        '<uuid:guid>/contact-update/',
        view=views.contact_update_api_view,
        name='contact_update'
    ),
    path(
        'fastcontact-create/',
        view=views.fast_contact_create_api_view,
        name='fast_contact_create'
    ),
    path(
        'fastcontact-list/',
        view=views.fast_contact_list_api_view,
        name='fast_contact_list'
    ),
    path(
        '<uuid:guid>/fastcontact-update/',
        view=views.fast_contact_update_api_view,
        name='fast_contact_update'
    ),
    path(
        'landing-list/',
        view=views.landing_data_list_api_view,
        name='landing_data_list'
    ),
    path(
        'landing-create/',
        view=views.landing_create_put_list_api_view,
        name='landing_create'
    ),
    path(
        '<uuid:guid>/landing-detail/',
        view=views.landing_create_put_list_api_view,
        name='landing_detail'
    ),
    path(
        '<uuid:guid>/landing-update/',
        view=views.landing_create_put_list_api_view,
        name='landing_update'
    ),
    path(
        '<uuid:guid>/landing-delete/',
        view=views.landing_create_put_list_api_view,
        name='landing_delete'
    ),
    path(
        'manager-guide-tourpackage-list/',
        view=views.manager_guide_tourpakcage_list_api_view,
        name='manager_tourpakcage_list'
    ),
    path(
        'tourpackage-pdf/<int:pk>',
        view=views.tourpackage_pdf_api_view,
        name='tourpackage_pdf'
    ),
]
