# Generated by Django 4.1.5 on 2023-07-03 10:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transport', '0001_initial'),
        ('flight', '0001_initial'),
        ('hotel', '0001_initial'),
        ('outfit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_expense', models.DecimalField(decimal_places=2, max_digits=20)),
                ('number_of_seat', models.PositiveIntegerField()),
                ('price_for_person', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Guide expectations', 'Guide expectations'), ('In adding users', 'In adding users'), ('Pending payment', 'Pending payment'), ('Submitted for visa', 'Submitted for visa'), ('Waiting for visa', 'Waiting for visa'), ('Ready to send', 'Ready to send'), ('Sent', 'Sent'), ('Waiting to arrive back', 'Waiting to arrive back'), ('Closed', 'Closed')], default='Created', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('hotel', models.ManyToManyField(to='hotel.hotel')),
                ('outfit', models.ManyToManyField(to='outfit.outfit')),
                ('transport', models.ManyToManyField(to='transport.transport')),
            ],
            options={
                'verbose_name': 'TourPackage',
                'verbose_name_plural': 'TourPackages',
                'ordering': ('-id',),
            },
        ),
    ]
