# Generated by Django 4.1.5 on 2023-08-18 12:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('hotel', '0001_initial'),
        ('outfit', '0001_initial'),
        ('transport', '0001_initial'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('phone_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='LandingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('landing_img', models.ImageField(null=True, upload_to='landing_imgs/.2023-08-18.12-39-41')),
            ],
            options={
                'verbose_name': 'LandingData',
                'verbose_name_plural': 'LandingDatas',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('price_for_person', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_data', models.JSONField(blank=True, null=True)),
                ('outfit_data', models.JSONField(blank=True, null=True)),
                ('hotel_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Guide expectations', 'Guide expectations'), ('In adding users', 'In adding users'), ('Pending payment', 'Pending payment'), ('Submitted for visa', 'Submitted for visa'), ('Waiting for visa', 'Waiting for visa'), ('Ready to send', 'Ready to send'), ('Sent', 'Sent'), ('Waiting to arrive back', 'Waiting to arrive back'), ('Closed', 'Closed')], default='Created', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('guide', models.ManyToManyField(to='employee.guide')),
                ('hotel', models.ManyToManyField(to='hotel.hotel')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourpackage_managers', to='employee.manager')),
                ('outfit', models.ManyToManyField(to='outfit.outfit')),
                ('transport', models.ManyToManyField(to='transport.transport')),
            ],
            options={
                'verbose_name': 'TourPackage',
                'verbose_name_plural': 'TourPackages',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TourPackageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('tourpackage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage')),
            ],
            options={
                'verbose_name': 'TourPackageBook',
                'verbose_name_plural': 'TourPackageBooks',
                'ordering': ('-id',),
            },
        ),
    ]
