# Generated by Django 4.1.5 on 2023-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FastContact',
        ),
        migrations.AlterField(
            model_name='contact',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-08-18.05-58-49'),
        ),
    ]
