# Generated by Django 4.1.5 on 2023-07-09 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackageCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('quantity_by_room_type', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remained_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage')),
            ],
            options={
                'verbose_name': 'TourPackage Calculation',
                'verbose_name_plural': 'TourPackage Calculations',
                'ordering': ('-id',),
            },
        ),
    ]
