# Generated by Django 4.1.5 on 2023-07-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_hotel_image'),
        ('package', '0002_tourpackagecalculation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackagecalculation',
            name='quantity_by_room_type',
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='hotel',
            field=models.ManyToManyField(related_name='tour_package', to='hotel.hotel'),
        ),
    ]
