# Generated by Django 4.1.5 on 2023-07-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_remove_tourpackagecalculation_quantity_by_room_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='number_of_seat',
            new_name='number_of_seats',
        ),
    ]
