# Generated by Django 4.1.5 on 2023-07-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_alter_departflight_day_of_week_and_more'),
        ('package', '0004_rename_number_of_seat_tourpackage_number_of_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='flight',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='depart_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.departflight'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='return_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.returnflight'),
        ),
    ]
