# Generated by Django 4.1.5 on 2023-08-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('flight', '0001_initial'),
        ('package', '0004_alter_landingdata_landing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-08-24.09-38-13'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flight.flight'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tourpackage_managers', to='employee.manager'),
        ),
    ]
