# Generated by Django 4.1.5 on 2023-07-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_remove_departflight_aviacompany_and_more'),
        ('hotel', '0015_alter_hotel_image'),
        ('package', '0005_remove_tourpackage_flight_tourpackage_depart_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='depart_flight',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='return_flight',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flight.flight'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='hotel',
            field=models.ManyToManyField(to='hotel.hotel'),
        ),
        migrations.DeleteModel(
            name='TourPackageCalculation',
        ),
    ]
