# Generated by Django 4.1.5 on 2023-08-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_guide_manager'),
        ('package', '0006_remove_tourpackage_depart_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourpackage_guides', to='employee.guide'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourpackage_managers', to='employee.manager'),
        ),
    ]
