# Generated by Django 4.1.5 on 2023-08-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0007_tourpackage_guide_tourpackage_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='hotel_additional_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='hotel_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='outfit_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
