# Generated by Django 4.1.5 on 2023-08-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0008_tourpackage_hotel_additional_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='hotel_additional_expense',
        ),
    ]
