# Generated by Django 4.1.5 on 2023-08-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_guide_manager'),
        ('package', '0009_remove_tourpackage_hotel_additional_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='guide',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='guide',
            field=models.ManyToManyField(to='employee.guide'),
        ),
    ]
