# Generated by Django 4.1.5 on 2023-08-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0010_remove_tourpackage_guide_tourpackage_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='currency',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
