# Generated by Django 4.1.5 on 2023-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_tourpackage_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='additional_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
