# Generated by Django 4.1.5 on 2023-08-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0012_alter_landingdata_landing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-08-31.10-39-07'),
        ),
    ]
