# Generated by Django 4.1.5 on 2023-09-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_alter_landingdata_landing_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-09-19.06-16-59'),
        ),
    ]
