# Generated by Django 4.1.5 on 2023-08-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0013_tourpackagebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackagebook',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
