# Generated by Django 4.1.5 on 2023-08-15 08:37

from django.db import migrations, models
import main.apps.package.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0014_tourpackagebook_is_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number_1', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('landing_img', models.ImageField(blank=True, null=True, upload_to=main.apps.package.models.upload_landing_images)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('-id',),
            },
        ),
    ]
