# Generated by Django 4.1.5 on 2023-10-14 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_alter_landingdata_landing_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
                ('mecca', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
                ('airplane', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
                ('plane', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
                ('airplane_wing', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
                ('visa', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
                ('wave', models.ImageField(null=True, upload_to='pdf_imgs/.2023-10-14.09-22-21')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-10-14.09-22-21'),
        ),
    ]
