# Generated by Django 4.1.5 on 2023-12-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0025_alter_landingdata_landing_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane_wing',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='logo',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='mecca',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='plane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='visa',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='wave',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-07.09-12-44'),
        ),
    ]
