# Generated by Django 4.1.5 on 2023-12-16 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0030_alter_landingdata_landing_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourpackageExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('num_of_people', models.PositiveIntegerField(default=0)),
                ('price_for_one', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'verbose_name': 'TourpackageExpense',
                'verbose_name_plural': 'TourpackageExpenses',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane_wing',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='logo',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='mecca',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='plane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='visa',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='wave',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-05-01'),
        ),
    ]
