# Generated by Django 4.1.5 on 2023-12-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0031_tourpackageexpense_alter_landingdata_landing_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackageexpense',
            name='tourpackage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='package.tourpackage'),
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane_wing',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='logo',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='mecca',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='plane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='visa',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='wave',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-16.13-14-58'),
        ),
    ]
