# Generated by Django 4.1.5 on 2023-12-17 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0032_tourpackageexpense_tourpackage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('communal_expense', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employee_salary', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('telephone', models.DecimalField(decimal_places=2, max_digits=20)),
                ('meet', models.DecimalField(decimal_places=2, max_digits=20)),
                ('taxi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employee_salary_mecca', models.DecimalField(decimal_places=2, max_digits=20)),
                ('field_1', models.DecimalField(decimal_places=2, max_digits=20)),
                ('field_2', models.DecimalField(decimal_places=2, max_digits=20)),
                ('field_3', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'MonthlyExpense',
                'verbose_name_plural': 'MonthlyExpenses',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='landingdata',
            name='landing_img',
            field=models.ImageField(null=True, upload_to='landing_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='airplane_wing',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='logo',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='mecca',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='plane',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='visa',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
        migrations.AlterField(
            model_name='pdfimage',
            name='wave',
            field=models.ImageField(null=True, upload_to='pdf_imgs/.2023-12-17.08-42-42'),
        ),
    ]
