# Generated by Django 4.1.5 on 2023-08-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_visapartner_visaclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visapartner',
            name='client',
        ),
        migrations.AddField(
            model_name='visapartner',
            name='visa_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.visaclient'),
        ),
    ]
