# Generated by Django 4.1.5 on 2023-08-08 14:44

from django.db import migrations, models
import main.apps.client.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_visapartner_client_visapartner_visa_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visaclient',
            options={'ordering': ('-id',), 'verbose_name': 'VisaClient', 'verbose_name_plural': 'VisaClients'},
        ),
        migrations.AddField(
            model_name='client',
            name='is_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='visa_file',
            field=models.FileField(null=True, upload_to=main.apps.client.models.upload_visa_file),
        ),
        migrations.AlterField(
            model_name='visaclient',
            name='visa_file',
            field=models.FileField(null=True, upload_to=main.apps.client.models.upload_visa_file),
        ),
    ]
