# Generated by Django 4.1.5 on 2023-08-09 07:33

from django.db import migrations, models
import main.apps.client.models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_visaclient_options_client_is_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='visa_file',
            field=models.FileField(null=True, upload_to=main.apps.client.models.upload_partner_visa_file),
        ),
    ]
