# Generated by Django 4.1.5 on 2023-08-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0011_tourpackage_currency'),
        ('client', '0005_partner_is_badge_partner_visa_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='outfit_size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='tour_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tourpackage_clients', to='package.tourpackage'),
        ),
    ]
