# Generated by Django 4.1.5 on 2023-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_outfit_size_alter_client_tour_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='outfit_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
