# Generated by Django 4.1.5 on 2023-09-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_client_passport_img_alter_client_visa_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='series',
        ),
        migrations.RemoveField(
            model_name='client',
            name='series_number',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='series',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='series_number',
        ),
        migrations.RemoveField(
            model_name='visaclient',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='visaclient',
            name='series',
        ),
        migrations.RemoveField(
            model_name='visaclient',
            name='series_number',
        ),
        migrations.RemoveField(
            model_name='visapartner',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='visapartner',
            name='series',
        ),
        migrations.RemoveField(
            model_name='visapartner',
            name='series_number',
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='passport_series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visaclient',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visaclient',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visaclient',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visaclient',
            name='passport_series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visapartner',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visapartner',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visapartner',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visapartner',
            name='passport_series',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_img',
            field=models.ImageField(null=True, upload_to='client_images/.2023-09-19.06-16-59'),
        ),
        migrations.AlterField(
            model_name='client',
            name='visa_file',
            field=models.FileField(null=True, upload_to='visa_files/.2023-09-19.06-16-59'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='pass_partner_images/.2023-09-19.06-16-59'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='visa_file',
            field=models.FileField(null=True, upload_to='pass_visa_files/.2023-09-19.06-16-59'),
        ),
        migrations.AlterField(
            model_name='visaclient',
            name='passport_img',
            field=models.ImageField(null=True, upload_to='visa_client_pass_imgs/.2023-09-19.06-16-59'),
        ),
        migrations.AlterField(
            model_name='visaclient',
            name='visa_file',
            field=models.FileField(null=True, upload_to='visa_client_files/.2023-09-19.06-16-59'),
        ),
        migrations.AlterField(
            model_name='visapartner',
            name='passport_image',
            field=models.ImageField(null=True, upload_to='visa_partner_pass_imgs/.2023-09-19.06-16-59'),
        ),
    ]
