# Generated by Django 4.1.5 on 2023-08-18 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('number_of_stars', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3)),
                ('booking_duration', models.CharField(max_length=100)),
                ('number_of_floor', models.PositiveIntegerField(default=0)),
                ('number_of_room', models.PositiveIntegerField(default=0)),
                ('nutrition', models.CharField(choices=[('AI', 'AI'), ('BB', 'BB'), ('FB', 'FB'), ('HB', 'HB'), ('HBT', 'HBT'), ('FBT', 'FBT')], max_length=100)),
                ('image', models.ImageField(null=True, upload_to='hotel_images/.2023-08-18.05-50-34')),
                ('single_room_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('double_room_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('triple_room_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('quadruple_room_price', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HotelCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('quantity_by_room_type', models.PositiveIntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prepayment', models.DecimalField(decimal_places=2, max_digits=20)),
                ('remained_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'HotelCalculation',
                'verbose_name_plural': 'HotelCalculations',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HotelBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('is_viewed', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
            options={
                'verbose_name': 'HotelBook',
                'verbose_name_plural': 'HotelBooks',
                'ordering': ('-id',),
            },
        ),
    ]
