# Generated by Django 4.1.5 on 2023-07-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_hotel_double_room_price_hotel_quadruple_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel_images/.2023-07-11.07-27-08'),
        ),
    ]
