# Generated by Django 4.1.5 on 2023-08-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel_images/.2023-08-24.11-57-02'),
        ),
    ]
