# Generated by Django 4.1.5 on 2023-08-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0037_alter_hotel_image_hotelbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbook',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel_images/.2023-08-14.11-08-22'),
        ),
    ]
