# Generated by Django 4.1.5 on 2023-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_guide_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidecalculation',
            name='remained_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='managercalculation',
            name='remained_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
