# Generated by Django 4.1.5 on 2023-08-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_guidecalculation_remained_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
