name: Parvoz CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install openssh-client -y
        
      - name: SSH into the server and deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@45.129.170.136 "\
          cd /home/projects/project/Parvoz-Express/ && \
          git pull origin master && \
          docker-compose -f production.yml up -d --build --remove-orphans"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
